packages:
  - packages/*

allowBuilds:
  '@keqingmoe/tree-sitter': set this to true or false
  '@ladybugdb/core': set this to true or false
  esbuild: set this to true or false
  falkordblite: set this to true or false
  keytar: set this to true or false
  tree-sitter-go: set this to true or false
  tree-sitter-java: set this to true or false
  tree-sitter-javascript: set this to true or false
  tree-sitter-python: set this to true or false
  tree-sitter-rust: set this to true or false
  tree-sitter-typescript: set this to true or false

ignoredBuiltDependencies:
  - '@keqingmoe/tree-sitter'
  - esbuild
  - keytar
  - tree-sitter-go
  - tree-sitter-java
  - tree-sitter-javascript
  - tree-sitter-python
  - tree-sitter-rust
  - tree-sitter-typescript

onlyBuiltDependencies: '["@keqingmoe/tree-sitter", "keytar"]'
