packages:
  - packages/*

onlyBuiltDependencies:
  - esbuild
  - keytar
  - tree-sitter
  - tree-sitter-go
  - tree-sitter-java
  - tree-sitter-javascript
  - tree-sitter-python
  - tree-sitter-rust
  - tree-sitter-typescript
