/**
 * CLAUDE.md Generator
 *
 * Generates a CLAUDE.md context file that includes:
 * - Project structure from the knowledge graph
 * - Recent decisions from the context manifold
 * - Deploy target status from deploy configs
 * - Bandit/scorer statistics
 */

import { DeployConfigLoader } from '../deploy/config-loader.js';
import type { DeployConfig } from '@cv-git/shared';
import type { GraphManager } from '../graph/index.js';

export interface ClaudeMdOptions {
  repoRoot: string;
  graph?: GraphManager;
  /** Include deploy status section */
  includeDeploy?: boolean;
}

export class ClaudeMdGenerator {
  private configLoader: DeployConfigLoader;

  constructor() {
    this.configLoader = new DeployConfigLoader();
  }

  /**
   * Generate the full CLAUDE.md content.
   */
  async generate(options: ClaudeMdOptions): Promise<string> {
    const sections: string[] = [];

    sections.push('# Project Context');
    sections.push('');
    sections.push('> Auto-generated by cv-git. Do not edit manually.');
    sections.push('');

    // Deploy status
    if (options.includeDeploy !== false) {
      const deploySection = await this.generateDeploySection(options);
      if (deploySection) sections.push(deploySection);
    }

    // Graph stats
    if (options.graph) {
      const graphSection = await this.generateGraphSection(options.graph);
      if (graphSection) sections.push(graphSection);
    }

    // Bandit stats
    if (options.graph) {
      const banditSection = await this.generateBanditSection(options.graph);
      if (banditSection) sections.push(banditSection);
    }

    return sections.join('\n');
  }

  /**
   * Generate deploy targets section from deploy/*.yaml configs.
   */
  private async generateDeploySection(options: ClaudeMdOptions): Promise<string | null> {
    let configs: DeployConfig[];
    try {
      configs = await this.configLoader.loadAll(options.repoRoot);
    } catch {
      return null;
    }

    if (configs.length === 0) return null;

    const lines: string[] = ['## Deploy Targets', ''];
    lines.push('| Target | Provider | Services | Status |');
    lines.push('|--------|----------|----------|--------|');

    for (const config of configs) {
      const serviceNames = config.services.map((s) => s.name).join(', ');
      let status = 'configured';

      // Try to get last deploy status from graph
      if (options.graph) {
        try {
          const results = await options.graph.query(`
            MATCH (d:DevOps {name: $name})
            RETURN d.status as status, d.lastRun as lastRun
          `, { name: config.target });

          if (results.length > 0) {
            status = (results[0].status as string) || 'configured';
          }
        } catch {
          // Graph may not be available
        }
      }

      lines.push(`| ${config.target} | ${config.provider} | ${serviceNames} | ${status} |`);
    }

    lines.push('');
    return lines.join('\n');
  }

  /**
   * Generate knowledge graph stats section.
   */
  private async generateGraphSection(graph: GraphManager): Promise<string | null> {
    try {
      const fileCount = await graph.query('MATCH (f:File) RETURN count(f) as count');
      const symbolCount = await graph.query('MATCH (s:Symbol) RETURN count(s) as count');

      const files = fileCount[0]?.count ?? 0;
      const symbols = symbolCount[0]?.count ?? 0;

      if (files === 0 && symbols === 0) return null;

      return [
        '## Knowledge Graph',
        '',
        `- Files: ${files}`,
        `- Symbols: ${symbols}`,
        '',
      ].join('\n');
    } catch {
      return null;
    }
  }

  /**
   * Generate bandit scorer statistics section.
   */
  private async generateBanditSection(graph: GraphManager): Promise<string | null> {
    try {
      const state = await graph.loadBanditState();
      if (!state) return null;

      const arms = state.arms instanceof Map ? state.arms : new Map(Object.entries(state.arms));
      let totalPulls = 0;
      let totalReward = 0;
      for (const arm of arms.values()) {
        totalPulls += (arm as any).pulls ?? 0;
        totalReward += (arm as any).totalReward ?? 0;
      }

      if (totalPulls === 0) return null;

      return [
        '## Context Scorer',
        '',
        `- Arms: ${arms.size}`,
        `- Total observations: ${totalPulls}`,
        `- Average reward: ${(totalReward / totalPulls).toFixed(3)}`,
        '',
      ].join('\n');
    } catch {
      return null;
    }
  }
}
